language: nodejs
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build

deploy:
 provider: surge
 skip_cleanup: true
 domain: ill-informed-vessel.surge.sh
 project: ./build/

on:
 branch: master